table 'business vw_abhi_vs_market'
	lineageTag: 304d9781-1113-454c-a75a-bb1c7a1dc082

	column age_band
		dataType: string
		lineageTag: 06cf2972-c934-439e-866f-c28f1ea15254
		summarizeBy: none
		sourceColumn: age_band
		sortByColumn: 'Age Band Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Age Band Sort'
		dataType: int64
		formatString: 0
		lineageTag: 1a3c5e7f-9b2d-4f6a-8c1e-3d5b7f9a2c4e
		summarizeBy: none
		sourceColumn: Age Band Sort

		annotation SummarizationSetBy = Automatic

	column si_label
		dataType: string
		lineageTag: f03e670d-9b87-42e1-9908-9b125727ed17
		summarizeBy: none
		sourceColumn: si_label
		sortByColumn: sum_insured

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column sum_insured
		dataType: double
		lineageTag: acd87b00-1832-4e5f-b382-2ac83b6f4637
		summarizeBy: sum
		sourceColumn: sum_insured

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abhi_premium
		dataType: int64
		formatString: 0
		lineageTag: 2f1556f1-8ce3-472f-b5dd-f19493a1ca20
		summarizeBy: sum
		sourceColumn: abhi_premium

		annotation SummarizationSetBy = Automatic

	column market_avg
		dataType: int64
		formatString: 0
		lineageTag: b0f77695-25f8-43ef-b16c-3159c9d153a3
		summarizeBy: sum
		sourceColumn: market_avg

		annotation SummarizationSetBy = Automatic

	column market_min
		dataType: int64
		formatString: 0
		lineageTag: bab40c57-d70a-46f9-b9b3-3903ea3cde26
		summarizeBy: sum
		sourceColumn: market_min

		annotation SummarizationSetBy = Automatic

	column market_max
		dataType: int64
		formatString: 0
		lineageTag: 5d4c653c-188b-4cdf-802f-4f01234a03f5
		summarizeBy: sum
		sourceColumn: market_max

		annotation SummarizationSetBy = Automatic

	column competitor_count
		dataType: int64
		formatString: 0
		lineageTag: 7e8dc0e9-47a1-4cf4-9b52-eef2b4a8b144
		summarizeBy: sum
		sourceColumn: competitor_count

		annotation SummarizationSetBy = Automatic

	column gap_rupees
		dataType: int64
		formatString: 0
		lineageTag: e5aa71ec-9262-413b-8278-512196f8b768
		summarizeBy: sum
		sourceColumn: gap_rupees

		annotation SummarizationSetBy = Automatic

	column price_index
		dataType: double
		lineageTag: 39a069ba-9257-4f70-bb30-88603f4079ed
		summarizeBy: sum
		sourceColumn: price_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column position
		dataType: string
		lineageTag: 69e2163e-bca9-4629-96a5-f329e5ddfb3a
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column is_cheapest
		dataType: int64
		formatString: 0
		lineageTag: c2906404-f14a-4850-aed9-c01bd3c663ea
		summarizeBy: sum
		sourceColumn: is_cheapest

		annotation SummarizationSetBy = Automatic

	column is_dearest
		dataType: int64
		formatString: 0
		lineageTag: 09a16335-a41c-4d6b-a661-745f3ad79485
		summarizeBy: sum
		sourceColumn: is_dearest

		annotation SummarizationSetBy = Automatic

	measure 'Last Refreshed' = "Last refreshed " & FORMAT(NOW(), "dd mmm yyyy hh:mm")
		lineageTag: 4b6d8f1a-3c5e-4a7b-9d2f-6e8b1a4c7d9f

	measure 'Avg Price Index (Reliable)' = CALCULATE(AVERAGE('business vw_abhi_vs_market'[price_index]), 'business vw_abhi_vs_market'[competitor_count] >= 4)
		formatString: 0.0
		lineageTag: efce368b-843a-472e-8a1b-7be422ecf9f5

	measure 'Avg Price Index (All Segments)' = AVERAGE('business vw_abhi_vs_market'[price_index])
		formatString: 0.0
		lineageTag: b9586952-54e8-4f20-b5cf-92fe18a16c4e

	measure 'Reliable Segment Count' = CALCULATE(COUNTROWS('business vw_abhi_vs_market'), 'business vw_abhi_vs_market'[competitor_count] >= 4)
		formatString: 0
		lineageTag: d9a7ad67-929e-4bf4-9f54-6c88bf12183a

	measure 'Thin Segment Count' = COUNTROWS('business vw_abhi_vs_market') - [Reliable Segment Count]
		formatString: 0
		lineageTag: 89b235b1-adf2-4510-917b-4671c3f863b3

	measure 'Segments Below Market % (Reliable)' = DIVIDE(CALCULATE(COUNTROWS('business vw_abhi_vs_market'), 'business vw_abhi_vs_market'[price_index] < 90, 'business vw_abhi_vs_market'[competitor_count] >= 4), [Reliable Segment Count])
		formatString: 0%
		lineageTag: 8af33a62-d850-400c-bc16-eaee159e776d

	measure 'Segments Above Market % (Reliable)' = DIVIDE(CALCULATE(COUNTROWS('business vw_abhi_vs_market'), 'business vw_abhi_vs_market'[price_index] > 105, 'business vw_abhi_vs_market'[competitor_count] >= 4), [Reliable Segment Count])
		formatString: 0%
		lineageTag: 7b270493-db13-4b2c-9682-cb2675d2d370

	measure 'Cheapest Segments (Reliable)' = CALCULATE(SUM('business vw_abhi_vs_market'[is_cheapest]), 'business vw_abhi_vs_market'[competitor_count] >= 4)
		formatString: 0
		lineageTag: 85a6c286-a6aa-4fda-85de-a7ae1898dfce

	measure 'Cheapest Segments (All)' = SUM('business vw_abhi_vs_market'[is_cheapest])
		formatString: 0
		lineageTag: 049f1286-4b2f-4982-b680-8eacd7d6a2d8

	measure 'Avg Premium Gap' = AVERAGE('business vw_abhi_vs_market'[gap_rupees])
		formatString: #,##0
		lineageTag: c5052fdc-dd08-4f6e-ba9c-246a766e4b17

	measure 'Gap Direction' = IF([Avg Premium Gap] < 0, "ABHI cheaper", "ABHI dearer")
		lineageTag: 9b6bddef-b742-498d-9c05-7a683c6b33df

	measure 'Price Index Label' = VAR v = AVERAGE('business vw_abhi_vs_market'[price_index]) VAR n = AVERAGE('business vw_abhi_vs_market'[competitor_count]) RETURN IF(ISBLANK(v), BLANK(), FORMAT(v, "0") & IF(n < 4, " (n=" & FORMAT(n, "0") & ")", ""))
		lineageTag: face35a6-59b8-4b9b-8108-e18e12482a89

	measure 'Price Index Cell Color' = VAR v = AVERAGE('business vw_abhi_vs_market'[price_index]) VAR n = AVERAGE('business vw_abhi_vs_market'[competitor_count]) RETURN SWITCH(TRUE(), ISBLANK(v), "#f2f2f2", n < 4, "#8a8a8a", v < 90, "#0ca30c", v <= 105, "#8a8a8a", "#d03b3b")
		lineageTag: b587dbf3-b2fb-4d79-a2dc-5ffa00c109b7

	measure 'Modal Position (Reliable)' = VAR PositionCounts = ADDCOLUMNS(VALUES('business vw_abhi_vs_market'[position]), "Cnt", CALCULATE(COUNTROWS('business vw_abhi_vs_market'), 'business vw_abhi_vs_market'[competitor_count] >= 4)) VAR TopRow = TOPN(1, PositionCounts, [Cnt], DESC) RETURN MAXX(TopRow, 'business vw_abhi_vs_market'[position])
		lineageTag: c6ddcad2-a39e-4915-91f8-aca595a8f676

	measure 'Modal Position Count (Reliable)' = VAR ModalPos = [Modal Position (Reliable)] RETURN CALCULATE(COUNTROWS('business vw_abhi_vs_market'), 'business vw_abhi_vs_market'[position] = ModalPos, 'business vw_abhi_vs_market'[competitor_count] >= 4)
		formatString: 0
		lineageTag: e04c9860-a3fa-44eb-8f2c-32c357cf77c0

	measure 'ABHI Cheapest Slab Premium' = MINX('business vw_abhi_vs_market', 'business vw_abhi_vs_market'[abhi_premium])
		formatString: #,##0
		lineageTag: 292b999c-378c-4f44-90d9-eac8eae81086

	measure 'ABHI Cheapest Slab Market Min' = VAR MinPremium = [ABHI Cheapest Slab Premium] RETURN CALCULATE(MAX('business vw_abhi_vs_market'[market_min]), 'business vw_abhi_vs_market'[abhi_premium] = MinPremium)
		formatString: #,##0
		lineageTag: 1f7b3f2a-6d4e-4a9c-8e2b-5c9a7d3e1b4f

	measure 'ABHI Cheapest Slab Label' = VAR MinPremium = [ABHI Cheapest Slab Premium] RETURN CALCULATE(MAX('business vw_abhi_vs_market'[age_band]) & " · " & MAX('business vw_abhi_vs_market'[si_label]), 'business vw_abhi_vs_market'[abhi_premium] = MinPremium)
		lineageTag: 8e5c1a2d-9f4b-4e6a-b3c7-2d8f1a6e9c5b

	measure 'ABHI Premium' = SUM('business vw_abhi_vs_market'[abhi_premium])
		formatString: #,##0
		lineageTag: 3a9d5c1e-7b4f-4a2d-9e6c-1f8b3d5a7c9e

	measure 'Market Avg Premium' = SUM('business vw_abhi_vs_market'[market_avg])
		formatString: #,##0
		lineageTag: 6c2e8f4a-1d9b-4e7c-a3f5-8b6d2c4e9a1f

	partition 'business vw_abhi_vs_market' = m
		mode: import
		source =
				let
				    Source = Sql.Database("AKSHAT\SQLEXPRESS", "INSURANCEDB"),
				    business_vw_abhi_vs_market = Source{[Schema="business",Item="vw_abhi_vs_market"]}[Data],
				    #"Added Age Band Sort" = Table.AddColumn(business_vw_abhi_vs_market, "Age Band Sort", each
				        if [age_band] = "18-25" then 1
				        else if [age_band] = "26-35" then 2
				        else if [age_band] = "36-45" then 3
				        else if [age_band] = "46-55" then 4
				        else if [age_band] = "56-65" then 5
				        else if [age_band] = "66+" then 6
				        else 99, Int64.Type)
				in
				    #"Added Age Band Sort"

	annotation PBI_ResultType = Table

