/*  Reference data
    The hand-curated rows: the eight insurers, their flagship products, published financials and policy-term flags. PREMIUM and the raw/clean PDF text are NOT here - those are extracted from the source PDFs by the pipeline.

    Run the sql/ files in numeric order against your target database — select
    it first in SSMS, or pass it in the connection string. These scripts
    deliberately contain no USE statement so they cannot redirect themselves.

    Afterwards, populate the fact tables with the Python pipeline:
        python Python/extract_products.py     seeds PRODUCT_MASTER
        python Python/run_all.py              PDFs -> raw -> clean -> PREMIUM
*/

-- COMPANY_MASTER: 8 curated rows
SET IDENTITY_INSERT [business].[COMPANY_MASTER] ON;
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (1, N'HDFC ERGO', N'https://www.hdfcergo.com', N'Mumbai');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (2, N'ICICI Lombard', N'https://www.icicilombard.com', N'Mumbai');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (3, N'Care Health', N'https://www.careinsurance.com', N'Gurugram');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (4, N'Star Health', N'https://www.starhealth.in', N'Chennai');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (5, N'Niva Bupa', N'https://www.nivabupa.com', N'New Delhi');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (6, N'Bajaj Allianz', N'https://www.bajajallianz.com', N'Pune');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (7, N'Tata AIG', N'https://www.tataaig.com', N'Mumbai');
INSERT INTO [business].[COMPANY_MASTER] ([company_id], [company_name], [website], [headquarters]) VALUES (8, N'ABHI', N'https://www.adityabirlacapital.com/healthinsurance', N'Mumbai');
SET IDENTITY_INSERT [business].[COMPANY_MASTER] OFF;
GO

-- PRODUCT_MASTER: 8 curated rows
SET IDENTITY_INSERT [business].[PRODUCT_MASTER] ON;
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (1, 1, N'Optima Secure', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (2, 2, N'Elevate', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (3, 3, N'Care Supreme', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (4, 4, N'Star Comprehensive', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (5, 5, N'ReAssure 2.0', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (6, 6, N'Health Guard', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (7, 7, N'MediCare Premier', N'Health Insurance', N'Individual');
INSERT INTO [business].[PRODUCT_MASTER] ([product_id], [company_id], [product_name], [insurance_type], [category]) VALUES (8, 8, N'Activ Health Platinum', N'Health Insurance', N'Individual');
SET IDENTITY_INSERT [business].[PRODUCT_MASTER] OFF;
GO

-- COMPANY_METRICS: 35 curated rows
SET IDENTITY_INSERT [business].[COMPANY_METRICS] ON;
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (2, 1, N'FY25', N'16229.43', N'15817.29', NULL, NULL, N'10.29', N'10.29', N'2.00', N'5.10', N'4862.39', N'8643.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (3, 1, N'FY24', N'18801.70', N'18567.56', NULL, NULL, N'11.36', N'11.36', N'1.68', NULL, N'3852.02', N'7238.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (4, 1, N'FY23', N'16873.14', N'16635.81', NULL, NULL, N'18.05', N'18.05', N'1.81', NULL, N'3615.96', N'5868.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (5, 1, N'FY22', N'13707.14', N'13497.55', NULL, NULL, N'15.57', N'15.57', N'1.64', NULL, N'3211.89', N'5421.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (6, 1, N'FY21', N'12443.93', N'12295.10', NULL, NULL, N'20.21', N'20.21', N'1.90', NULL, N'2926.86', N'4895.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (7, 8, N'FY25', N'4940.41', N'4821.71', NULL, NULL, N'0.35', N'0.10', N'1.84', NULL, N'1478.97', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (8, 8, N'FY24', N'3701.32', N'3701.32', NULL, NULL, N'-17.07', N'-4.74', N'1.67', NULL, N'1073.37', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (9, 8, N'FY23', N'2717.03', N'2717.03', NULL, NULL, N'-17.46', N'-6.48', N'2.63', NULL, N'1253.01', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (10, 8, N'FY22', N'1726.67', N'1726.67', NULL, NULL, N'-59.65', N'-17.11', N'1.77', NULL, N'522.14', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (11, 8, N'FY21', N'1300.64', N'1300.64', NULL, NULL, N'-49.84', N'-13.21', N'1.82', NULL, N'396.58', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (12, 6, N'FY25', N'21582.92', N'21416.81', NULL, NULL, N'15.25', NULL, N'3.25', NULL, N'12012.22', N'31729.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (13, 6, N'FY24', N'20630.00', N'20472.68', NULL, NULL, N'14.30', NULL, N'3.49', NULL, N'10841.28', N'30168.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (14, 6, N'FY23', N'15486.93', N'15336.64', NULL, NULL, N'14.06', NULL, N'3.91', NULL, N'9588.57', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (15, 6, N'FY22', N'13788.06', N'13688.59', NULL, NULL, N'16.04', NULL, N'3.44', NULL, N'8348.61', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (16, 6, N'FY21', N'12624.38', N'12569.53', NULL, NULL, N'18.65', NULL, N'3.45', NULL, N'7132.94', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (17, 2, N'FY25', N'28257.74', N'26833.36', NULL, NULL, NULL, N'3.63', NULL, NULL, NULL, N'78.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (18, 2, N'FY24', N'25594.16', N'24776.11', NULL, NULL, NULL, N'3.03', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (19, 2, N'FY23', N'21771.83', N'21025.09', NULL, NULL, NULL, N'3.14', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (20, 2, N'FY22', N'18562.39', N'17976.87', NULL, NULL, NULL, N'2.50', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (21, 2, N'FY21', N'14320.33', N'14003.09', NULL, NULL, NULL, N'3.75', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (22, 5, N'FY25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'9.10', NULL, N'0.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (23, 5, N'FY24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'0.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (24, 5, N'FY23', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'0.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (25, 5, N'FY22', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'0.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (26, 5, N'FY21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'0.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (27, 4, N'FY25', N'16781.36', N'16716.20', NULL, NULL, N'9.20', N'3.11', N'2.21', N'33.00', N'7022.03', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (28, 4, N'FY24', N'15254.45', N'15254.45', NULL, NULL, N'13.33', N'4.76', N'2.21', NULL, N'6339.24', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (29, 4, N'FY23', N'12952.47', N'12952.47', NULL, NULL, N'11.39', N'4.06', N'2.14', NULL, N'5430.13', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (30, 4, N'FY22', N'11463.47', N'11463.47', NULL, NULL, N'-23.05', N'-7.70', N'1.67', NULL, N'4513.88', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (31, 4, N'FY21', N'9388.54', N'9388.54', NULL, NULL, N'-31.16', N'-10.34', N'2.22', NULL, N'3484.34', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (32, 7, N'FY25', N'18159.57', N'17702.83', NULL, NULL, N'15.16', N'2.16', N'1.81', N'9.20', N'5527.95', NULL, NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (33, 7, N'FY24', N'15422.55', N'15090.90', NULL, NULL, N'14.65', N'2.02', N'2.09', NULL, N'4676.52', N'2510227.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (34, 7, N'FY23', N'13448.30', N'13176.01', NULL, NULL, N'13.86', N'2.15', N'1.94', NULL, N'3991.59', N'1950581.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (35, 7, N'FY22', N'10685.80', N'10024.97', NULL, NULL, N'13.21', N'2.06', N'1.97', NULL, N'3438.54', N'1667217.00', NULL, NULL);
INSERT INTO [business].[COMPANY_METRICS] ([metric_id], [company_id], [financial_year], [gwp], [gdpi], [csr], [icr], [roe], [roa], [solvency_ratio], [market_share], [net_worth], [aum], [combined_ratio], [claim_turnaround_time]) VALUES (36, 7, N'FY21', N'8574.14', N'8042.06', NULL, NULL, N'15.00', N'2.51', N'2.22', NULL, N'2984.40', N'1292911.00', NULL, NULL);
SET IDENTITY_INSERT [business].[COMPANY_METRICS] OFF;
GO

-- HEALTH_FEATURES: 7 curated rows
SET IDENTITY_INSERT [business].[HEALTH_FEATURES] ON;
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (9, 1, N'30 Days', N'3 Years', N'Single Private Room', 1, 1, 1, 1, 1, 60, 60, 1, 1, 1, 1, NULL, 1);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (10, 2, N'30 Days', N'3 Years', N'Single Private AC Room', 1, 1, 0, 0, 1, 90, 180, 1, 1, 1, 1, 2000, 0);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (11, 4, N'30 Days', N'3 Years', N'Mentioned', 1, 1, 1, 1, 1, 15, 90, 1, 1, 1, 1, NULL, 0);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (12, 5, NULL, N'3 Years', N'Single Private Room', 0, 1, 0, 1, 1, NULL, 180, 0, 1, 1, 1, NULL, 0);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (13, 6, N'30 Days', N'3 Years', N'At Actuals', 1, 1, 1, 1, 1, 60, 90, 1, 1, 0, 1, 20000, 1);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (14, 7, N'30 Days', N'2 Years', N'Mentioned', 1, 1, 1, 1, 1, 60, 200, 1, 1, 1, 1, 20000, 1);
INSERT INTO [business].[HEALTH_FEATURES] ([feature_id], [product_id], [waiting_period], [ped_waiting], [room_rent], [opd_cover], [maternity_cover], [restoration], [ncb], [ayush_cover], [pre_hospitalization], [post_hospitalization], [day_care], [organ_donor], [domiciliary_treatment], [annual_health_checkup], [ambulance_cover], [consumables_cover]) VALUES (15, 8, N'60 Days', N'3 Years', N'Single Private AC Room', 1, 1, 0, 1, 1, 30, 30, 1, 1, 1, 1, NULL, 1);
SET IDENTITY_INSERT [business].[HEALTH_FEATURES] OFF;
GO
